#!/usr/bin/env bash

echo You need to have working ruby setup for development:
echo Ruby 1.8.7
echo bundler >= 1.0.0
echo "----------"
echo installing required libraries
sudo apt-get install libnotify-bin
sudo apt-get instal libwxgtk-2.8-{0,dev}



echo Running bundler
bundle install vendor --without test

